ACTIVE = "ACTIVE"
SUSPENDED = "SUSPENDED"
WAITING = "WAITING"
STOPPED = "STOPPED"
STATUS_CHOICES = (
    (WAITING, "WAITING"),
    (ACTIVE, "ACTIVE"),
    (SUSPENDED, "SUSPENDED"),
    (STOPPED, "STOPPED")
)


