# Generated by Django 4.0.3 on 2022-03-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
                ('url', models.TextField(max_length=15, unique=True)),
                ('post_default_status', models.CharField(choices=[('WAITING', 'WAITING'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('STOPPED', 'STOPPED')], default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BlogBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_publish_policy', models.CharField(choices=[('POST+', 'post without review from editor'), ('POST', 'post after review approve from editor'), ('UNPOST', "can't post"), ('NON', 'not')], max_length=10)),
                ('default_membership_policy', models.CharField(choices=[('WAITING', 'WAITING'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('STOPPED', 'STOPPED')], max_length=10)),
                ('style', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EditorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('DEL', 'can delete article'), ('SUS', 'can suspend '), ('REVIEW', 'can review and approve article'), ('NON', 'non')], max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('permissions', models.ManyToManyField(to='blog.editorpermission')),
            ],
        ),
    ]
